import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '../src/styles/animation.css';
import Navbar from '@/components/organisms/navbar/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ar' dir='rtl'>
      <body className={inter.className}>
        <Navbar />
        {children}
        {/* added footer here */}
      </body>
    </html>
  );
}
